trace1 = {
  x: ['Twitter Followers', 'Pinterest Followers', 'Facebook Likes', 'Instagram Followers', 'YouTube Subscribers', 'YouTube Videos', 'YouTube Views', '', '', ''], 
  y: [1592789, 3800, 759525, 588764, 1744287, 669, 302681131, '', '', ''], 
  marker: {color: 'rgb(255, 0, 254)'}, 
  name: 'iJustine', 
  opacity: 0.78, 
  type: 'bar'
};

trace2 = {
  x: ['Twitter Followers', 'Pinterest Followers', 'Facebook Likes', 'Instagram Followers', 'YouTube Subscribers', 'YouTube Videos', 'YouTube Views', '', '', ''], 
  y: [59682, 1533, 9820476, 454175, 1666614, 47, 34159285, '', '', ''], 
  marker: {color: 'rgb(151, 153, 155)'}, 
  name: 'Apple', 
  type: 'bar'
};
data = [trace1, trace2];

layout = {
  annotations: [
    {
      x: -0.28125, 
      y: 6.47323647279, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -26.7109375, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '1.5M', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 0.090625, 
      y: 5.03774452329, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -26.7109375, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '59K', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 0.746875, 
      y: 3.8350350521, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '3.8K', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 1.0859375, 
      y: 3.44706425494, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '1.5K', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 2.059375, 
      y: 7.26857660696, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '9.8M', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 1.6875, 
      y: 6.10466421548, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '760K', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 2.7046875, 
      y: 6.04646859591, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '589K', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 3.065625, 
      y: 5.87188173719, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '454K', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 3.7109375, 
      y: 6.5120335525, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '1.7M', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 4.071875, 
      y: 6.49263501264, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '1.7M', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 4.728125, 
      y: 3.0978905375, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '669', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 5.1, 
      y: 1.95337668588, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '47', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 5.7015625, 
      y: 8.737584263, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '302M', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }, 
    {
      x: 6.0734375, 
      y: 7.74731702007, 
      align: 'center', 
      arrowcolor: '', 
      arrowhead: 1, 
      arrowsize: 1, 
      arrowwidth: 0, 
      ax: -10, 
      ay: -27.390625, 
      bgcolor: 'rgba(0,0,0,0)', 
      bordercolor: '', 
      borderpad: 1, 
      borderwidth: 1, 
      font: {
        color: 'rgb(67, 67, 67)', 
        family: 'Raleway, sans-serif', 
        size: 12
      }, 
      opacity: 1, 
      ref: 'plot', 
      showarrow: false, 
      text: '34M', 
      xanchor: 'auto', 
      xref: 'x', 
      yanchor: 'auto', 
      yref: 'y'
    }
  ], 
  autosize: false, 
  bargap: 0.29, 
  bargroupgap: 0.15, 
  barmode: 'group', 
  boxgap: 0.3, 
  boxgroupgap: 0.3, 
  boxmode: 'overlay', 
  dragmode: 'zoom', 
  font: {
    color: 'rgb(67, 67, 67)', 
    family: 'Raleway, sans-serif', 
    size: 12
  }, 
  height: 550, 
  hidesources: false, 
  hovermode: 'x', 
  legend: {
    x: 0.0104584854015, 
    y: 0.977435897436, 
    bgcolor: 'rgba(255, 255, 255, 0.5)', 
    bordercolor: 'rgb(255, 255, 255)', 
    borderwidth: 1, 
    font: {
      color: 'rgb(67, 67, 67)', 
      family: 'Raleway, sans-serif', 
      size: 12
    }, 
    traceorder: 'normal', 
    xanchor: 'auto', 
    yanchor: 'auto'
  }, 
  margin: {
    r: 80, 
    t: 80, 
    autoexpand: true, 
    b: 120, 
    l: 80, 
    pad: 2
  }, 
  paper_bgcolor: '#fff', 
  plot_bgcolor: '#fff', 
  separators: '.,', 
  showlegend: true, 
  smith: false, 
  title: 'This is from the Plotly Library, all the attributes can be modified, this is the Histogram', 
  titlefont: {
    color: '', 
    family: '', 
    size: 14
  }, 
  width: 800, 
  xaxis: {
    anchor: 'y', 
    autorange: true, 
    autotick: true, 
    domain: [0, 1], 
    dtick: 1, 
    exponentformat: 'e', 
    gridcolor: 'rgb(255, 255, 255)', 
    gridwidth: 1, 
    linecolor: 'rgb(255, 255, 255)', 
    linewidth: 1, 
    mirror: true, 
    nticks: 0, 
    overlaying: false, 
    position: 0, 
    range: [-0.5, 6.5], 
    rangemode: 'normal', 
    showexponent: 'all', 
    showgrid: true, 
    showline: true, 
    showticklabels: true, 
    tick0: 0, 
    tickangle: 30, 
    tickcolor: 'rgb(255, 255, 255)', 
    tickfont: {
      color: 'rgb(67, 67, 67)', 
      family: '', 
      size: 0
    }, 
    ticklen: 5, 
    ticks: 'outside', 
    tickwidth: 1, 
    title: 'X', 
    titlefont: {
      color: 'rgb(255, 255, 255)', 
      size: 0
    }, 
    type: 'category', 
    zeroline: true, 
    zerolinecolor: '#000', 
    zerolinewidth: 1
  }, 
  yaxis: {
    anchor: 'x', 
    autorange: false, 
    autotick: true, 
    domain: [0, 1], 
    dtick: 1, 
    exponentformat: 'B', 
    gridcolor: 'rgba(240, 240, 240, 0.8)', 
    gridwidth: 1, 
    linecolor: 'rgb(255, 255, 255)', 
    linewidth: 1, 
    mirror: true, 
    nticks: 0, 
    overlaying: false, 
    position: 0, 
    range: [1.29382633071, 9.1345159533], 
    rangemode: 'normal', 
    showexponent: 'all', 
    showgrid: true, 
    showline: true, 
    showticklabels: true, 
    tick0: 0, 
    tickangle: 'auto', 
    tickcolor: 'rgb(255, 255, 255)', 
    tickfont: {
      color: 'rgb(67, 67, 67)', 
      family: '', 
      size: 0
    }, 
    ticklen: 5, 
    ticks: 'outside', 
    tickwidth: 1, 
    title: 'Y', 
    titlefont: {
      color: 'rgb(255, 255, 255)', 
      family: '', 
      size: 0
    }, 
    type: 'log', 
    zeroline: true, 
    zerolinecolor: '#000', 
    zerolinewidth: 1
  }
};

Plotly.plot('histo', {
  data: data,
  layout: layout
});